### ISSUE TITLE
username field should default to lower-case

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-android#10]
# Current behaviour

On the login screen, when clicking on the Username field, the input defaults to uppercase, so on Tecno phone you have to press `shift` **twice** before you can enter a lowercase letter to start your username.

# Desired behaviour

If input started in lowercase, then life would be easier (for me).  Worth checking if real users generally have usernames starting with upper or lowercase letters.

We could also make the username case-insensitive.

**Comment by garethbowen** [comment]
This was a typo in the medic-api login page.

**Comment by alxndrsn** [comment]
:+1:
