### ISSUE TITLE
Build app with Android 11 Developer Preview. Ensure app still functions

### ISSUE THREAD

**Issue by newtewt** [medic/medic-android#108]
Android 11 is releasing this year(2020). We should get ahead of the curve by building a test version and ensuring it still functions properly when we target android 11 sdk and build our min version.

**Comment by garethbowen** [comment]
Related: #106

**Comment by derickl** [comment]
Starting August 2021, new apps will be required to target API level 30 (Android 11) **and use the Android App Bundle publishing format**. Starting November 2021, all app updates will be required to target API level 30 (Android 11). Apps with a download size of more than 150 MB are now supported by Play Asset Delivery and Play Feature Delivery.

**Comment by garethbowen** [comment]
Closing this issue as a duplicate of #164 which has a little more info.
