### ISSUE TITLE
Compliance with Play Store developer policies for PII collection disclosure

### ISSUE THREAD

**Issue by derickl** [medic/medic-android#111]
Shadow issue: https://github.com/medic/medic-projects/issues/7536

**Comment by garethbowen** [comment]
This is blocking projects so we need to start working on this right away. Scheduling for 3.10.0.

**Comment by dianabarsan** [comment]
This is ready for AT on branch `5917-goodbye-periodic-gpsing`. 

Please test it against cht-core branch `5917_better-gps`. 

For Android >= 6, you should _not_ get a permission request the first time you boot the app. Instead, you should get a permission request when you create/edit a report or open a task. 
The permission request will keep appearing on the next create/edit/open, until you accept or "deny and don't show again". 

For Android 5 and 4, you should get no permissions requests, as in these versions, permissions are granted automatically when the app is installed. 

Against a cht-core version that is not `5917_better-gps` and Android >= 6, location permission will never be requested, never be granted and Geolocation data will not be recorded on reports.

**Comment by ngaruko** [comment]
LGTM.
For Android 5 (and maybe earlier versions), there permissions prompt before the app is installed and with Android 7 (and maybe adjacent versions), there is a 'bold' claim that the app does not require any access... but I guess these are Google-level warnings. See screenshots below, courtesy of @mrjones-plip .

**Android 5 - Install**
![image](https://user-images.githubusercontent.com/6979995/89471787-23fbd780-d7d3-11ea-8a55-04d65f725131.png)

**Android 7 Install -**
![image](https://user-images.githubusercontent.com/6979995/89471815-32e28a00-d7d3-11ea-888e-563d001341ab.png)
 
**Android 7 - Edit report**
![image](https://user-images.githubusercontent.com/6979995/89472081-b8fed080-d7d3-11ea-85ae-271eb04841c8.png)
 
**Android 10 -** 
![image](https://user-images.githubusercontent.com/6979995/89472119-cae07380-d7d3-11ea-9506-0914561bc235.png)

Pinging @derickl to have a look at those and give it a quick test on different versions they might have available.

**Comment by dianabarsan** [comment]
Merged into `master`.
