### ISSUE TITLE
Support Android 10+

### ISSUE THREAD

**Issue by njogz** [medic/medic-android#114]
The app [crashes on Android 10](https://github.com/medic/medic-android/issues/106#issuecomment-675845229) because crosswalk is no longer supported. There is an [issue](https://github.com/medic/cht-core/issues/5723) to investigate dropping crosswalk altogether but that is currently not a feasible solution since we have a lot of users still using Android 4.4. The alternative is to build multiple APKs and drop crosswalk only for newer versions of Android. A possible side effect is that users already using crosswalk can lose all their data once they are upgraded to a version of the app using webview. The webview APKs will therefore have to target Android 10+

**Comment by garethbowen** [comment]
> The webview APKs will therefore have to target Android 10+

This is a good opportunity for us to get a non-crosswalk version of the app built so we can test our support before rolling it out to more users.

The other option is to investigate ways to migrate data from crosswalk to webview which means it could be easily rolled out to all devices from Android 5+.

Publishing an apk just for Android 10+ seems like a really solid first step, and we can investigate migration for Android 5-9 after we've shown it works.

As part of this issue we need to evaluate and contrast the benefits of webview vs TWA.

**Comment by dianabarsan** [comment]
I'm using the app successfully on Android 10, no errors. 

I think this was only happening in a certain development branch?

**Comment by njogz** [comment]
Yes. It crashes when the target SDK is updated.

**Comment by garethbowen** [comment]
This is being solved as part of this issue: https://github.com/medic/medic-android/issues/106
