### ISSUE TITLE
readme.md link to "Connecting to the server locally" doesn't exist

### ISSUE THREAD

**Issue by mrjones-plip** [medic/medic-android#115]
On our [repo home page](https://github.com/medic/medic-android/), there's a section titled "Connecting to the server locally" with a link to: https://github.com/medic/medic#testing-locally-with-devices . Given the target repo `medic` has long since been renamed to `cht-core`, I think this link to `testing-locally-with-devices` is very old.  Not sure where it should go just yet, so filing this ticket so we don't forget to fix the source [readme.md](https://github.com/medic/medic-android/blob/7c8a9d1/README.md) file.

**Comment by garethbowen** [comment]
My guess is it should link here: https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#testing-locally-with-devices

**Comment by mrjones-plip** [comment]
Thanks @garethbowen  - I'll even give you the review on the PR - you're welcome!! ;)

**Comment by garethbowen** [comment]
Merged.
