### ISSUE TITLE
Cannot log in into offline profile

### ISSUE THREAD

**Issue by magp18** [medic/medic-android#118]
I followed the tutorial to push the application to my tablet, and everything works when logging in as administrator with ngrok URL. However as soon as I create a new role for a CHW supervisor to have offline functionality and log out to log back in as that role, the application does not start. The error I get then is : "Loading error, please check your connection". Afterwards it is impossible to get back to the log in screen.

**Comment by newtewt** [comment]
@magp18  are you adding the role to the user you were logged in as then logging out and back in? Trying to nail down the reproduction steps a bit more.

**Comment by magp18** [comment]
No, I am logging in as admin and then creating a new user with the role e.g. CHW to that user. Then I log out and try to log in with that created user.

**Comment by newtewt** [comment]
I follow your steps and I don't get the same error but I get one I think we need to solve for sure.  I get an privileges issue.

![image](https://user-images.githubusercontent.com/10531066/94943967-8527ea80-04a6-11eb-9b6e-9113e8a13fe5.png)

Which version of the webapp are you running? You can find this by logging in as admin and then going to Hamburger Menu > About

Did you build the Android app, user one of our releases on github, or the one on the appstore?

Are you going to the ngrok url that is https?

You can clear the apps cache by going to android settings. This will be as if reinstalled the app and get you to the log in if you need a workaround.

**Comment by magp18** [comment]
Yes I have gotten that same error once too, but I do not remember the role I used. 
The most frequent one is this one:

![Screenshot 2020-10-03 at 19 12 30](https://user-images.githubusercontent.com/33976946/94997636-cefaf880-05ac-11eb-999b-0687d777ec27.png)

But with Data entry role I get this one:

![Screenshot 2020-10-03 at 19 11 53](https://user-images.githubusercontent.com/33976946/94997661-f225a800-05ac-11eb-86f4-cbde61d19b85.png)

I get this when accessing about as admin, however version is blank:

![Screenshot 2020-10-03 at 19 22 13](https://user-images.githubusercontent.com/33976946/94997801-c9ea7900-05ad-11eb-9185-07b2c8a6051f.png)

To build the app I followed your tutorial described [here](https://github.com/medic/medic-android/), with the additional indications described in [here](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#testing-locally-with-devices) where you advice us to use ngrok, so I did use ngrok too. 

I tried clearing the cache already but did not help to get back to the log in screen.

**Comment by magp18** [comment]
Additionally, I am not sure if this is intended but I tried to create a new profile (not for offline this time) to test it but I cannot access targets or the tasks, I get this message:
on the targets tab: 

![Screenshot 2020-10-05 at 09 45 10](https://user-images.githubusercontent.com/33976946/95053923-610c1980-06f1-11eb-8f25-5570347e4bc1.png)

On the task tab:

![Screenshot 2020-10-05 at 09 45 27](https://user-images.githubusercontent.com/33976946/95053967-7123f900-06f1-11eb-8420-567b1fdd45c0.png)

I am not logging in as an admin, I am logging in with a role that I created called all_online, with all the permissions checked, in the Roles and Permissions tab.

**Comment by newtewt** [comment]
You'll need an offline user. The error you were presenting  "Loading error, please check your connection". is usually due to a service worker needing a valid https certificate. That's why we specify the `ngrok` use.  Can you attempt to log in using chrome against your ngrok url with the offline user?

**Comment by magp18** [comment]
Thank you for your suggestion, I did try that. I am using chrome and the ngrok link that I have running. I try to log in with the user with an offline profile but the error persists

![medicmobile_noconnection](https://user-images.githubusercontent.com/33976946/95095616-8c135f00-072b-11eb-8479-66a728cc5c12.PNG)

**Comment by newtewt** [comment]
Are you able to view the browser console and see what errors are presented?

**Comment by magp18** [comment]
Yes, the error in the console:

![error_offline](https://user-images.githubusercontent.com/33976946/95096274-58850480-072c-11eb-8981-95f9d7458f90.PNG)

**Comment by magp18** [comment]
http://9c4c29a895e0.ngrok.io/

**Comment by newtewt** [comment]
Can you use the https://9c4c29a895e0.ngrok.io/ version and try again?

**Comment by magp18** [comment]
It is working now on my browser, thank you! However it still does not work on the tablet.

**Comment by newtewt** [comment]
On your tablet. I would uninstall the app and when you are prompted to select a url to log in. Make sure to use the https url.

**Comment by magp18** [comment]
How did you manage to make it work on the browser, in case that happens again? 
On the tablet: I uninstalled and installed it again as suggested, but as soon as I try to connect with https, I get an error saying it is unable to contact the server. I only manage to log in with http when using the tablet.

**Comment by magp18** [comment]
Thank you, it does work when I use the browser! Do you have any ideas why it is not possible with the app?

**Comment by newtewt** [comment]
I would double check the https url and make sure no types, check for spaces at beginning and end.  Ngrok also logs the traffic. Would make sure you see it showing up there as that would confirm it's reaching your local machine.

**Comment by magp18** [comment]
Yes I am sure it is the correct link as I copied from the browser, and when I take the "s" out of "htpps" it works perfectly. It does not reach my local machine, ngrok does not log anything. I have the link on the app and click save and instantly an error shows saying that it was unable to contact the server. 
However, errors are logged after using make to push the application to the device, and this is the error I get:

**Comment by newtewt** [comment]
I am unable to use the `make` method because of my environment. Can you try using the unbranded version we have on the play store?

**Comment by magp18** [comment]
Did you manage to enter the URL with https instead of http? I uninstalled mine and installed it from google store and I still have the same error that it cannot contact the server.

**Comment by newtewt** [comment]
I am stumped as to why it wouldn't work in the app but is in the browser. Which version of android are you running?

**Comment by magp18** [comment]
I have the android version 4.4.2

**Comment by newtewt** [comment]
I know that we ran into an issue with 4.x versions of android and the ssl cert failing because of a newer version of it being produced. I assume that's what you're running into. Because the android app currently uses an older version of chrome bundled with the app.

**Comment by magp18** [comment]
Does that mean that only more recent versions might not encounter such problems, as opposed to versions 4.x which might?
Thank you anyway for your time!

**Comment by newtewt** [comment]
That is correct. Android has a limitation with certain ssl certs in that version.  The recommended solution is to upgrade android if possible.

**Comment by newtewt** [comment]
@magp18  do you feel this issue is resolved?  I'd like to close it out.

**Comment by magp18** [comment]
Yes, thank you again!
