### ISSUE TITLE
Branded signed APKs are no longer available

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-android#138]
Seems that branded signed APKs are no longer built after v0.6. These APKs are required for ops team to test and upgrade medic-android releases. Until a plan is in place for us to get these APKs, we should revert this change and publish the APKs to at least GitHub releases.

**Comment by garethbowen** [comment]
The workaround is to branch and tag the flavour in the same way that new flavours are published. While this is more work for the ops team (sorry!) it's not a blocker for this release. Reducing priority accordingly.

**Comment by kennsippell** [comment]
That workaround isn't documented clearly, isn't broadly understood, isn't suitable for relevant members of the ops team.  The system was working fine before the v0.6 commits. We went from having using automated build outputs to not having any useful build outputs.... from where I sit, this is a regression.

**Comment by garethbowen** [comment]
I've switched to using GH Actions which is a little more flexible. Now on tag all apks are built and attached to the GH release as before. Publishing to the Play Store is still a manual action.
