### ISSUE TITLE
Warn users if system date is wrong

### ISSUE THREAD

**Issue by abbyad** [medic/medic-android#14]
To avoid major reporting date issues, it would be helpful to have a notice that the system date is clearly wrong (eg pre 2015) and some generic comment on how to set it. This has apparently been an issue for previous Android deployment for LG.

**Comment by alxndrsn** [comment]
Also at https://github.com/medic/medic-webapp/issues/1658

**Comment by alxndrsn** [comment]
Fixed in medic-webapp.
