### ISSUE TITLE
Android Location Permission Skipped, Unable to send form

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-android#145]
**Describe the bug**
This is rather an edge case and an intermittent error where a) the second prompt for location permission (android) is skipped upon pressing ‘Turn on’ on the new location access prompt. b) the submit button hangs and report is not submitted. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the app - all clear data if app already installed and login
2. Attempt to submit report
3. On first location permission prompt, ignore and close all the apps, including medic
4. Go to phone settings and change language settings, select another language
5. Open/restart Medic app
6. Add report > On first prompt press 'Turn on'
7. The android prompt is not shown
8. Complete form and press submit
9. Form not submitted, see screen recording below

**Expected behaviour**
The app should show the android permission prompt 
![image](https://user-images.githubusercontent.com/6979995/103718858-9eec4700-502c-11eb-8403-b40fddb0a77b.png)

**Logs**
[verbose.zip](https://github.com/medic/medic-android/files/5773457/verbose.zip)

**Screenshots**

https://user-images.githubusercontent.com/6979995/103718948-d0fda900-502c-11eb-84be-0a022f8c7182.mov

**Environment**
- Instance: gama-cht.dev.medicmobile.org
- Browser: Chrome
- Client platform: android 10
- App: medic-android
- Version: v0.7.0

**Additional context**
We have a tight deadline to comply with with [Google Play Store’s requirement for prominent disclosure](https://support.google.com/googleplay/android-developer/answer/9799150#prominent_disclosure). Since this is an intermittent edge case scenario that is not a usual user workflow, it is in our best interest to fix this later, ie after #136 . Unfortunately when the user gets to this error, the app is pretty much unusable, the best work around involves clearing data on the device via `app info > storage > clear` data.  Your thoughts @abbyad @garethbowen @craig-landry ? Assigning to @mrsarm since he has been working on the app.

**Comment by abbyad** [comment]
>  best work around involves clearing data on the device via app info > storage > clear data

Clearing device data for existing users has pretty severe consequences for users and patients, so to me this sounds like a failed test case that would block the release.

**Comment by ngaruko** [comment]
> > best work around involves clearing data on the device via app info > storage > clear data
> 
> Clearing device data for existing users has pretty severe consequences for users and patients, so to me this sounds like a failed test case that would block the release.

@mrsarm is working on this. He has been able to replicate a sort of similar bug that seems to occur more often than this. Hopefully the next release will have this fixed.

**Comment by ngaruko** [comment]
@abbyad  My suggestion was about the chances of occurring - I think it is pretty low. In reality, one has to be pretty intentional to break the app for it to happen. 
_One other way I was able to reproduce it, slightly similar was:
Open app > form> new dialog >close medic…without deciding
Open phone settings > change language >
Open medic >form > our dialog > press ‘turn on’
Android dialog appears > Do nothing and close medic
Open medic again >form > our dialog > Press turn on
NOW - the android dialog is skipped and form won’t submit_

Quite a convoluted process, that’s why I thought it is not really something likely to happen in real life, and that, although it looks severe when it happens, we could work on it later, if it threatens the on time release of the app since it has been a little hard on the dev side to replicate it.

**Comment by mrsarm** [comment]
Comments on this [here](https://github.com/medic/medic-android/issues/136#issuecomment-755822963).

**Comment by ngaruko** [comment]
For the form submission hanging and locking the app,  I realised there is a less fatal work around (which does not involve clearing data), but rather using the `force stop` option in app info. 
![image](https://user-images.githubusercontent.com/6979995/103982255-026ea400-51e8-11eb-8595-158ffb321aff.png)

**Comment by ngaruko** [comment]
Most probably fixed with [this PR](https://github.com/medic/medic-android/pull/142#discussion_r554028590) in  #136
