### ISSUE TITLE
`Back` button quits the app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-android#2]
Observed: pressing physical `back` button exits the app
Expected: pressing `back` should navigate back a page within the app

**Comment by garethbowen** [comment]
This code fixes the back button for tab navigation: http://stackoverflow.com/questions/20188952/back-button-for-previous-page-on-android-webview-not-working

However if you've selected a message it doesn't work properly. We'll need to hook in to the JS already implemented on the soft back button in the filters bar.

**Comment by alxndrsn** [comment]
This might do the job.
```java
        public void onBackPressed() {
                if(container != null && container.canGoBack()) {
-                       container.goBack();
+                       container.loadUrl("javascript:window.history.go(-1)");
                } else super.onBackPressed();
        }
```

**Comment by alxndrsn** [comment]
Apparently this is OK now.
