### ISSUE TITLE
Free space warning is busted

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-android#21]
Free-space warning was shown on a phone with the following storage usage:

![2016-08-05_13 43 25_720](https://cloud.githubusercontent.com/assets/191496/17438554/b2459a66-5b23-11e6-8659-5c1710fa6b62.png)

**Comment by estellecomment** [comment]
I've seen it busted, on the storage-usage branch, when the app was on SD card. Maybe it's confused by the SD card.

I didn't see the warning on the master branch app in same situation though.

**Comment by alxndrsn** [comment]
Re-open if the bug recurs.
