### ISSUE TITLE
Opening the admin console through webapp requires user to close and reopen the app

### ISSUE THREAD

**Issue by newtewt** [medic/medic-android#57]
Logging in as an admin user to the android app allows us to see the admin console. This opens in a new tab/window. Once the user navigates here they cannot return to the medic webapp without closing and opening the app. Low priority as I assume most admin users won't be using the app to configure but it should be handled. Using the hardware back closes the app and could possibly be registered to navigate back in this instance. 

Reproduction steps: Using a pixel 2 with android 8.1.0

Open App
Login in as admin user
Tap the hamburger menu  dropdown
Tap the configuration.

**Comment by SCdF** [comment]
> Low priority as I assume most admin users won't be using the app to configure

None of them do. Last I checked (things have changed in 3.0.0) the configuration portion of the app didn't even have mobile CSS

**Comment by garethbowen** [comment]
Stefan is right - we do not support admins on mobile resolutions.

@newtewt I'm thinking we should just remove the configuration link in the hamburger menu. You could still manually type the URL in but it'll make it harder to get there by accident. What do you think?

**Comment by newtewt** [comment]
@garethbowen  this looks good on those screens under 400px. I would merge but the comment seems a little lacking.

**Comment by garethbowen** [comment]
Merged. Thanks!
