### ISSUE TITLE
Issue in running make

### ISSUE THREAD

**Issue by shahinraza1** [medic/medic-android#60]
Hello developer,
I am getting the below issues on running make. Can you resolve for this. I am installing the app locally in genymotion virtual device.
https://pastebin.com/EazaW64c

**Comment by alxndrsn** [comment]
hi @sahinraza, it sounds like there's no native lib available for the architecture you're trying to deploy to.  Can you change the architecture that the genymotion virtual device is running on to ARM?

**Comment by sahinraza** [comment]
Yes I have installed the ARM on my genymotion emulator. The app is builded successfully. But on opening the opening the app on device I have three options beta dev, Alpha dev & git hub. On clicking any of these I am getting message that , unfortunately app has been stopped.

**Comment by sahinraza** [comment]
I am getting this in terminal
https://pastebin.com/8yn1MBJR

**Comment by alxndrsn** [comment]
I've not seen that problem before, but google & stackoverflow suggest either:

1. you're using `arm64`, but only `armeabi-v7a` is supported, or
2. you need to change `EmbeddedBrowserActivity` to extend `XWalkActivity`

Maybe try switching the emulator's processor architecture again and see if that helps.

**Comment by garethbowen** [comment]
Please reopen if the workarounds Alex suggested don't work.
