### ISSUE TITLE
Expose device information in medic-android so we can store it against monthly telemetry readings

### ISSUE THREAD

**Issue by SCdF** [medic/medic-android#64]
It would be really helpful to be able to add hardware-specific information into our monthly telemetry documents that you can't find out from the browser.

Off the top of my head that could be:
 - Phone make and model
 - android major version and patch level
 - Max and free disk space
 - RAM, CPU, GPU (unless that's covered by make and model? Probably best to be explicit)
 - Network capacity re: their sim card (this is may be hard because we might just catch them at a bad time or whatever. It would have to be a static truth that was representative regardless of when we compiled it).

This would be exposed to medic-webapp via the JS bridge.

Code links to follow telemetry merge.

**Comment by garethbowen** [comment]
Telemetry is merged, so let's get this added!

**Comment by kennsippell** [comment]
From https://github.com/medic/medic/issues/5540, some memory metrics for consideration are:

* Runtime.maxMemory
* ActivityManager.getMemoryClass
* MemoryInfo.availMemory
* MemoryInfo.threshold
* Chrome's performance.memory (although they are quantized)

**Comment by wtekeu** [comment]
Ready for AT, medic-android: `64-expose-device-info-to-webapp`, cht-core: `64-expose-device-info-to-webapp`

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/69319448-0bc74500-0ca4-11ea-826c-68c0ed9b05e5.png)

**Comment by wtekeu** [comment]
@ngaruko I changed the way I get the number of cores, please give it a try.

Also, `downSpeed == upSpeed == 1048576` because they correspond to the max link speed available for your device and connection type. You are probably using wifi of type AC.

**Comment by ngaruko** [comment]
Looks better. Thanks @wtekeu 
![image](https://user-images.githubusercontent.com/6979995/69502998-20445f80-0f7a-11ea-966a-9e761630a421.png)
