### ISSUE TITLE
Only allow webview to access expected URLs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-android#66]
If a URL is injected into our page it's possible to redirect the user to a different domain and risk exposing PHI. Block navigation to any site other than the right one.

**Comment by garethbowen** [comment]
AT:

1. Make sure you have a version of the app with this feature installed.
2. Inject a link to google.com (or wherever) in to the page (use dev tools if you have to).
3. Click on the link and make sure you can't access the page.

Also make sure you _can_ access all the links you need to access.

**Comment by ngaruko** [comment]
LGTM 
Tested on `gamma.dev` master (v3.4)
