### ISSUE TITLE
Webapp URL errors cover the Save button

### ISSUE THREAD

**Issue by abbyad** [medic/medic-android#8]
When the error comes up you can edit the text, but can't retry the save/connection because the error covers the Save button:
![image](https://cloud.githubusercontent.com/assets/789512/9411401/c03ec2ee-47f3-11e5-8033-31e94842d425.png)

On the Tecno Y4 Android 4.4, the surest way to get rid of the message is to press the settings button since it doesnt have any side effects. Pressing the volume also works, but shows the volume bar. The power and menu buttons exit the app, but don't clear the error. The back button clears the error and closes the app.

**Comment by alxndrsn** [comment]
Editing the textfield will remove the error message.  For normal users, I can't see it's common that they'll want to retry the same URL repeatedly.

**Comment by abbyad** [comment]
Unfortunately the error is not cleared when editing the text on the Tecno Y4. I can add the add name or remove it and the error persists.
