### ISSUE TITLE
Target API level requirements from August 2019

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-android#86]
This error appears in the Google Play Console when publishing updates to `medic-android`.

```
Target API level requirements from August 2019
Warning:

Your app currently targets API level 26 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.

From August 2019, new apps must target at least Android 9.0 (API level 28).
From November 2019, app updates must target Android 9.0 (API level 28).

Tip:

Change your app's target API level. Learn how
```

**Comment by kennsippell** [comment]
Ready for AT on `bump-28`

**Comment by newtewt** [comment]
I have built and run the unbranded version locally and ran it against gamma.dev.  I've tested on one 64bit (Pixel 2) and 2 32bit devices(Tecno J5, WX3) and the app is functioning as expected.  I think it would be good to merge this and then evaluate the apks generated after to ensure they work as expected.

**Comment by kennsippell** [comment]
I see you tagged and released this as https://github.com/medic/medic-android/releases/tag/v0.4.32

**Comment by newtewt** [comment]
Closing this out as it was already tested and a tag was created for this version.
