### ISSUE TITLE
Enable largeHeap setting in the android manifest since our footprint is large

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-android#88]
We should set the [largeHeap](https://developer.android.com/guide/topics/manifest/application-element) attribute in the Android manifest since we (via XWalk alone, before our app even starts) are frequently above Android's memory class. 

This should be done along-side continued efforts to reduce our memory footprint.

**Comment by kennsippell** [comment]
Since this is a 1-liner config-only change, got approved to add this into 3.7 today at product team meeting.

**Comment by newtewt** [comment]
Ran through the app on my three phones built against master. App is still functioning.
