### ISSUE TITLE
Failure to upload APKs to Play Store prevents APKs being published to GitHub

### ISSUE THREAD

**Issue by derickl** [medic/medic-android#91]
After adding a new APK flavor (and tagging a release), upload to Play Store fails with the following error:

```
Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name
```

This likely points to the upload script expecting the app to have existed on the play store which is not the case for new flavours.

It would be best to delink publishing to GitHub from successfully uploading the APK to the play store.

**Comment by garethbowen** [comment]
This should just work, or we should at least document how to do it right the first time. Pushing to GH before trying Play Store sounds like a good idea so at least you get the apk with which to manually create the app.

**Comment by garethbowen** [comment]
Delaying as there is a documented workaround.

**Comment by gopi4edu** [comment]
Following are the steps followed to publish the app in playstore:
1.added new flavour in build.gradle file 
2.selected the new flavour as build variant
3.added ' - fastlane deploy flavor:medic_new'
And finally generated app bundle to upload in playstore.
I didn't face any issue during the process.

**Comment by garethbowen** [comment]
During the switch to GH Actions I fixed this by publishing the apks and not publishing to the Play Store. I raised an issue for [reintroducing the Play Store publishing step](#144) and we'll ensure this happens _after_ the apks are added to the release in GH so we don't regress here.
