### ISSUE TITLE
Set target audience in all android apps on the play store

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-android#92]
We've just received this email from Google:

>  We’re writing to let you know that you have not yet completed the Target audience and content section of the Play Console for at least one of your apps. All developers were asked to fill out this section for all apps by September 1, 2019.
> Your app may be subject to removal from Google Play if you do not provide this information in Play Console. 

Go through all of the apps in the play store and ensure they all have the target audience set.

**Comment by garethbowen** [comment]
@abbyad informs me he's completed this, closing.

**Comment by abbyad** [comment]
Thanks @garethbowen, I didn't realize that there was an issue open for this when I got started on it.
